module "rke" {
source  = "../../"
ssh_key_pub= "${var.ssh_key_pub}"
ssh_key= "${var.ssh_key}"
ssh_user= "${var.ssh_user}"
external_network_id= "${var.external_network_id}"
floating_ip_pool= "${var.floating_ip_pool}"
image_name= "${var.image_name}"
master_flavor_name= "${var.master_flavor_name}"
master_count= "${var.master_count}"
service_flavor_name= "${var.service_flavor_name}"
service_count= "${var.service_count}"
ignore_docker_version= "${var.ignore_docker_version}"
edge_flavor_name= "${var.edge_flavor_name}"
edge_count= "${var.edge_count}"
os_username= "${var.os_username}"
os_password= "${var.os_password}"
os_auth_url= "${var.os_auth_url}"
os_tenant_id= "${var.os_tenant_id}"
os_tenant_name= "${var.os_tenant_name}"
os_domain_name= "${var.os_domain_name}"
}
